import Head from "next/head";
import Header from "@/components/Header";
import ProjectList from "@/components/ProjectList";
import style from "./index.module.scss";
import classnames from "classnames/bind";

const cx = classnames.bind(style);

export default function Home() {
  return (
    <>
      <Head>
        <title>Cozy world</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="google-site-verification" content="90Rn0cwEI5P0gvwSWaN0_RdH7pGFuQSU08WBzXBsy7Y" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cx("container")}>
        <Header></Header>
        <ProjectList />
      </main>
    </>
  );
}
